# Generated by Django 6.0.4 on 2026-04-14 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('piso', models.PositiveIntegerField()),
                ('lista', models.BooleanField(default=True)),
                ('nota', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(choices=[('ESTANDAR', 'Estandar'), ('SUITE', 'Suite'), ('PREMIUM', 'Premium')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('capacidad', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('info_camas', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'verbose_name': 'Tipo cuarto',
                'verbose_name_plural': 'Tipos cuarto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_reserva', models.CharField(db_index=True, max_length=12, unique=True)),
                ('nombre_huesped', models.CharField(max_length=200)),
                ('email_huesped', models.EmailField(max_length=254)),
                ('telefono_huesped', models.CharField(max_length=30)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_huespedes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('REGISTRADA_ENTRADA', 'Entrada registrada'), ('REGISTRADA_SALIDA', 'Salida registrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=25)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal_reserva', models.CharField(default='web', max_length=20)),
                ('pagada', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, default='')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.habitacion')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PrecioNocheReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo_fin_semana', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_estadia_larga', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recargo_ocupacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_noche', to='api.reserva')),
            ],
            options={
                'verbose_name': 'Precio por noche',
                'verbose_name_plural': 'Precios por noche',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='api.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='EntradaListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_huesped', models.CharField(max_length=200)),
                ('email_huesped', models.EmailField(max_length=254)),
                ('telefono_huesped', models.CharField(max_length=30)),
                ('fecha_entrada_preferida', models.DateField()),
                ('fecha_salida_preferida', models.DateField()),
                ('cantidad_huespedes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dias_flexibles', models.PositiveIntegerField(default=2)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('EXPIRADA', 'Expirada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('notificada_en', models.DateTimeField(blank=True, null=True)),
                ('retencion_hasta', models.DateTimeField(blank=True, null=True)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lista_espera', to='api.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Entrada lista de espera',
                'verbose_name_plural': 'Entradas lista de espera',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_salida__gt', models.F('fecha_entrada'))), name='reserva_salida_mayor_entrada'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('habitacion', 'fecha_entrada', 'fecha_salida'), name='reserva_unica_habitacion_fechas'),
        ),
        migrations.AlterUniqueTogether(
            name='precionochereserva',
            unique_together={('reserva', 'fecha')},
        ),
        migrations.AddConstraint(
            model_name='entradalistaespera',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_salida_preferida__gt', models.F('fecha_entrada_preferida'))), name='lista_espera_salida_mayor_entrada'),
        ),
    ]
