# Generated by Django 6.0.4 on 2026-04-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reserva_no_traslape_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradalistaespera',
            name='es_flexible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entradalistaespera',
            name='fecha_entrada_asignada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entradalistaespera',
            name='fecha_salida_asignada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entradalistaespera',
            name='habitacion_retenida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_retenidas', to='api.habitacion'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='retenida_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='retenida_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitacion_retencion', to='api.entradalistaespera'),
        ),
    ]
